name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: generate_and_push
        run: make generate_and_push
      - name: deploy
        run: make deploy
      - name: Check for changes
        id: changes
        run: |
          git fetch
          if [ -z "$(git diff origin/main)" ]; then
            echo "No changes to push"
            exit 0
          fi
      - name: Commit and Push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add output log"
          git push origin main
      
      
    